# Generated by Django 6.0.2 on 2026-09-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('question', models.TextField()),
                ('geometry_type', models.CharField(blank=True, max_length=80)),
                ('dimension', models.CharField(blank=True, max_length=8)),
                ('operation', models.CharField(max_length=120)),
                ('operation_label', models.CharField(blank=True, max_length=160)),
                ('result', models.JSONField()),
                ('explanation', models.JSONField()),
                ('visualization', models.JSONField()),
                ('response', models.JSONField()),
                ('response_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'response_hash'), name='unique_solved_problem_per_session_response')],
            },
        ),
    ]
